### ISSUE TITLE
Some questions about code

### ISSUE THREAD

**Issue by zweny** [nadgeri14/KGPool#3]
Hi：
here are some problems while i reproduce your experimental results:

1. NYT dataset shoule be save in which folder?' '**KGPool/relation_extraction/NYT**'[ps:train.py line47]  or '**NYT folder align with KGPool**‘ [ps: data_loader.py line15]  .  because **_vertexSet missed_** but dont know why 

2. NYT dataset dont have '**NYT/dataset_context_en_all_TOKENS.json**' but '**NYT/dataset_context_en_all.json**' [data_loader.py line17]

3. '**glove.6B**'  should be save in which folder?   '**KGPool/data**'[ps:train.py line52]  or  '**NYT/glove.6B**' [ps:data_loader.py line38]

4. Compile error:
```
ERROR:test:Failed after 0:04:08!
Traceback (most recent calls WITHOUT Sacred internals):
  File "train.py", line 162, in main
    test_as_indices = list(graphs_to_indices(test_set, word2idx, property2idx, max_sent_len, embeddings=embeddings, position2idx=position2idx))
  File "/root/KGPool/Context-Aggregator/parsing/legacy_sp_models.py", line 232, in to_indices_with_real_entities_and_entity_nums_with_vertex_padding
    if len(g['edgeSet']) > 0:
TypeError: string indices must be integers
```

Your reply will be higly appreciated。Thank！

**Comment by nadgeri14** [comment]
Hi, 
Thanks for your interest in our work. 

1. NYT dataset shoule be save in which folder? 
- Ideally, you can save the NYT dataset in any folder ideally just ensure the path remains the same in both files.[ps:train.py line47 and ps: data_loader.py line15], preferred path would be 'KGPool/relation_extraction/NYT'

2.  NYT dataset dont have 'NYT/dataset_context_en_all_TOKENS.json' but 'NYT/dataset_context_en_all.json'
- You can download the dataset from the previous baseline [RECON](https://github.com/ansonb/RECON#dataset) it contains all the necessary dataset. 

3. 'glove.6B' should be save in which folder? 
- Sorry for the typo, ideally both of them refer to the same glove embedding, hence you can use any one of them, ensuring the path remains same for both of them. 

4. Compile error:
- The error is probably due to the wrong dataset file being processed, the dataset files is from previous baseline [RECON](https://github.com/ansonb/RECON#dataset).

Hope this helps. Please reach out for further issues. 

Best 
Abhishek

**Comment by zweny** [comment]
Hi 
Thank you for your prompt reply！

About **Dataset** ：
The [NYT](https://drive.google.com/file/d/1VhY3i3SoLS3XZvtsk_BmpZgN5cjITlij/view) dataset  from the previous baseline  [RECON](https://github.com/ansonb/RECON#dataset) contains 'dataset_context_en_all.json' ， but in data_loader.py[line 17], the specific filename is 'dataset_context_en_all_TOKENS.json'  , **Are they the same file**？

Best Wishes

**Comment by nadgeri14** [comment]
Hi 
The contents remain the same, except 'dataset_context_en_all_TOKENS.json'  is tokenized using the tokenizer of nltk. 

Best
Abhishek

**Comment by zweny** [comment]
Hi
how can i get the file ‘dataset_context_en_all_TOKENS.json’?   [sorry about bothering you, i am just a nlp new-beginner :) ]
thank!

**Comment by nadgeri14** [comment]
Hi 
No issues :) 
You can refer to this [link](https://www.nltk.org/api/nltk.tokenize.html). I have used the word_tokenize function. 

For the file dataset_context_en_all.json, use the above function to tokenise the following keys for each entity. 
- desc
- alias
- en_instances

for example, for the key `m.05gf08` after tokenization, you should get the [following](https://colab.research.google.com/drive/1btqg4BTVAPEti7vJA4vo0JUEG0aaGeg8?usp=sharing)

**Comment by LOUGBERTI** [comment]
> Hi how can i get the file ‘dataset_context_en_all_TOKENS.json’? [sorry about bothering you, i am just a nlp new-beginner :) ] thank!

Hello, what is the result of running kgpool with wikidata
